### ISSUE TITLE
grunt 运行出错

### ISSUE THREAD

**Issue by idreamsoft** [fex-team/umeditor#370]
Compiling dist/utf8-php/umeditor.js -> dist/utf8-php/umeditor.min.js
Warning: dist/utf8-php/umeditor.js:1906: ERROR - object literals cannot contain duplicate keys in ES5 strict mode
    isFillChar: function (node, isInStart) {
    ^

1 error(s), 0 warning(s)
 Use --force to continue.

Aborted due to warnings.

**Comment by Phinome** [comment]
`isFillChar` 这个函数重复定义了，在 ES5 严格模式下会报警告，删除掉第一个就好
