### ISSUE TITLE
段落格式设置，字体设置，字号设置无效

### ISSUE THREAD

**Issue by jemmy-tang** [fex-team/umeditor#390]
求解

**Comment by zadnj** [comment]
修改： UM.ui.define( widgetName, ( function(){ 的 tpl
-  tpl: "<ul class=\"dropdown-menu edui-combobox-menu  <%if (comboboxName!=='') {%> edui-combobox-<%=comboboxName%><%}%>\" unselectable=\"on\" onmousedown=\"return false\" role=\"menu\" aria-labelledby=\"dropdownMenu\">" +
                "<%if(autoRecord) {%>" +
                "<%for( var i=0, len = recordStack.length; i<len; i++ ) {%>" +
                "<%var index = recordStack[i];%>" +
                "<li class=\"<%=itemClassName%><%if( selected == index ) {%> edui-combobox-checked<%}%>\" data-item-index=\"<%=items[index]%>\" unselectable=\"on\" onmousedown=\"return false\">" +
                "<span class=\"edui-combobox-icon\" unselectable=\"on\" onmousedown=\"return false\"></span>" +
                "<label class=\"<%=labelClassName%>\" style=\"<%=itemStyles[ index ]%>\" unselectable=\"on\" onmousedown=\"return false\"><%=items[index]%></label>" +
                "</li>" +
                "<%}%>" +
                "<%if( i ) {%>" +
                "<li class=\"edui-combobox-item-separator\"></li>" +
                "<%}%>" +
                "<%}%>" +
                "<%for( var i=0, label; label = items[i]; i++ ) {%>" +
                "<li class=\"<%=itemClassName%><%if( selected == i ) {%> edui-combobox-checked<%}%> edui-combobox-item-<%=label%>\"data-item-index=\"<%=label%>\" unselectable=\"on\" onmousedown=\"return false\">" +
                "<span class=\"edui-combobox-icon\" unselectable=\"on\" onmousedown=\"return false\"></span>" +
                "<label class=\"<%=labelClassName%>\" style=\"<%=itemStyles[ i ]%>\" unselectable=\"on\" onmousedown=\"return false\"><%=label%></label>" +
                "</li>" +
                "<%}%>" +
                "</ul>",

修改： initSelectItem

-  var $li = $(this), index = $li.attr('data-item-index');
                    //ie
                    if(!Array.indexOf){
                        Array.prototype.indexOf = function(el){
                            for (var i=0,n=this.length; i<n; i++){
                                if (this[i] === el){
                                    return i;
                                }
                            }
                            return -1;
                        }
                    }
                    var key  =  index;
                    var newIndex = me.data('options').value.indexOf(key),newValue = key;
                    me.trigger('comboboxselect', {
                        index: newIndex,
                        label: $li.find(labelClass).text(),
                        value: newValue
                    }).select( newIndex );
