### ISSUE TITLE
插入的自定义css样式不起作用

### ISSUE THREAD

**Issue by awswse111** [fex-team/umeditor#393]
切换到html源码，插入css样式，再点html切换回来，源码中的样式已经被过滤掉了，请问怎样解决。

例如源代码中插入：
-------------------------------------------------------------------------------
<style>
.red{ color: red}
</style>
<span class="red"></span>
-------------------------------------------------------------------------------
如何在切换html后保留样式

**Comment by Phinome** [comment]
修改 umeditor.config.js 里的白名单将 style 标签添加进去
