### ISSUE TITLE
官网提供的demo无法修改字体，字体大小和段落等等

### ISSUE THREAD

**Issue by razonyang** [fex-team/umeditor#410]
官网提供的demo无法修改字体，字体大小和段落等等http://ueditor.baidu.com/website/umeditor.html

**Comment by Phinome** [comment]
bug 已经修复。

**Comment by razonyang** [comment]
@Phinome 希望释放个新版本，最新的1.2.3有这个问题。：）

**Comment by Phinome** [comment]
嗯，正在上传中

**Comment by Phinome** [comment]
还是原来的地址，版本号没变是因为并没有更新，之前修改 xss 漏洞的时候遗留下的问题。已验证没有问题。
