### ISSUE TITLE
难用、过时

### ISSUE THREAD

**Issue by dmyaszs** [fex-team/umeditor#620]
垃圾

**Comment by jialiu830205** [comment]
你这种人真讨厌，长了张烂嘴，不合你意的就喷垃圾。你才是最大的垃圾。

**Comment by sherwin** [comment]
你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.

**Comment by dmyaszs** [comment]
> 你这种人真讨厌，长了张烂嘴，不合你意的就喷垃圾。你才是最大的垃圾。

你个智障

**Comment by dmyaszs** [comment]
> 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.

智障！反正是别人做的屎，你都吃 是吧？

**Comment by sherwin** [comment]
> > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> 
> 智障！反正是别人做的屎，你都吃 是吧？

所以这个issue发起之前, 你舔得什么味. 不合你口味吗.

**Comment by sherwin** [comment]
> > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> 
> 智障！反正是别人做的屎，你都吃 是吧？

还知道丢脸了, 关闭了.

**Comment by dmyaszs** [comment]
..

> > > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> > 
> > 
> > 智障！反正是别人做的屎，你都吃 是吧？
> 
> 所以这个issue发起之前, 你舔得什么味. 不合你口味吗.



> > > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> > 
> > 
> > 智障！反正是别人做的屎，你都吃 是吧？
> 
> 还知道丢脸了, 关闭了.

着不住 你们这群 已经习惯吃屎的蛆

**Comment by sherwin** [comment]
> ..
> 
> > > > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> > > 
> > > 
> > > 智障！反正是别人做的屎，你都吃 是吧？
> > 
> > 
> > 所以这个issue发起之前, 你舔得什么味. 不合你口味吗.
> 
> > > > 你厉害,自己写一个啊, 用别人的干嘛. 在这丢脸.
> > > 
> > > 
> > > 智障！反正是别人做的屎，你都吃 是吧？
> > 
> > 
> > 还知道丢脸了, 关闭了.
> 
> 着不住 你们这群 已经习惯吃屎的蛆

说自己是屎???
